Repository steemit/condenser, pull requests merged in 2018-04, with the labels that each got.

#2675 add Japanese language
  src/app/Main.js
  src/app/Translator.js
  src/app/locales/counterpart/ja.js
  src/app/locales/ja.json
Labels: 1

#2660 remove user related ssr
  package.json
  src/app/Main.js
  src/app/components/App.jsx
  src/app/components/modules/Header/index.jsx
  src/app/components/pages/Post.jsx
  src/app/components/pages/PostsIndex.jsx
  src/app/components/pages/PostsIndex.scss
  src/app/locales/en.json
  src/app/redux/UserReducer.js
  src/app/utils/ChainValidation.js
  src/db/tarantool.js
  src/server/app_render.jsx
  src/server/server.js
  src/shared/UniversalRender.jsx
  yarn.lock
Labels: WIP

#2652 profile and cover image uploader
  src/app/components/modules/Settings.jsx
  src/app/locales/en.json
Labels: 2, needs-review
