Repository steemit/condenser, pull requests merged in 2019-09, with the labels that each got.

#3500 Bug: Fix an exception caused during page load
  src/app/components/elements/GptAd.jsx
  src/app/redux/FetchDataSaga.js
Labels: bug

#3499 Add Ability to Pin/Unpin a Community Post
  src/app/components/cards/PostFull.jsx
  src/app/locales/en.json
Labels: communities

#3518 Add subscribe/unsubscribe button to community index
  src/app/components/elements/SubscribeButton.jsx
  src/app/components/elements/SubscribeButtonContainer.jsx
  src/app/components/pages/PostsIndex.jsx
Labels: communities

#3519 Add ability to mute a post
  src/app/components/cards/Comment.jsx
  src/app/components/cards/PostFull.jsx
  src/app/components/elements/MuteButton.jsx
  src/app/components/elements/MuteButtonContainer.jsx
  src/app/components/modules/MutePost.jsx
  src/app/locales/en.json
Labels: communities

#3532 reoganize discussion_idx
  src/app/components/cards/PostsList.jsx
  src/app/components/elements/SortOrder/index.jsx
  src/app/components/pages/PostsIndex.jsx
  src/app/components/pages/Topics.jsx
  src/app/components/pages/UserProfile.jsx
  src/app/redux/FetchDataSaga.js
  src/app/redux/FetchDataSaga.test.js
  src/app/redux/GlobalReducer.js
  src/app/redux/GlobalReducer.test.js
Labels: WIP

#3536 Select community when posting
  src/app/components/all.scss
  src/app/components/cards/CategorySelector.jsx
  src/app/components/elements/PostCategoryBanner.jsx
  src/app/components/elements/PostCategoryBanner.scss
  src/app/components/elements/PostCategoryBannerContainer.jsx
  src/app/components/elements/ReplyEditor.jsx
  src/app/components/pages/PostsIndex.jsx
  src/app/redux/FetchDataSaga.js
  src/app/redux/GlobalReducer.js
Labels: communities

#3534 Add Community Settings Editor
  src/app/components/elements/SettingsEditButton.jsx
  src/app/components/elements/SettingsEditButtonContainer.jsx
  src/app/components/modules/CommunitySettings.jsx
  src/app/components/pages/PostsIndex.jsx
  src/app/locales/en.json
Labels: communities
