Repository steemit/condenser, pull requests merged in 2019-10, with the labels that each got.

#3116 Add srcset to images
  src/app/components/cards/MarkdownViewer.scss
  src/app/components/pages/UserProfile.jsx
  src/app/utils/ProxifyUrl.js
  src/app/utils/ProxifyUrl.test.js
  src/app/utils/SanitizeConfig.js
  src/shared/HtmlReady.js
Labels: needs-review

#3540 edit user title
  src/app/assets/stylesheets/app.scss
  src/app/components/cards/Comment.jsx
  src/app/components/cards/PostFull.jsx
  src/app/components/elements/Author/index.jsx
  src/app/components/elements/Icon.jsx
  src/app/components/elements/Icon.scss
  src/app/components/elements/Reputation.jsx
  src/app/components/elements/UserTitleEditButton.jsx
  src/app/components/modules/UserTitle.jsx
  src/app/locales/en.json
  src/app/redux/GlobalReducer.js
Labels: communities

#3541 comm role mgmt
  src/app/ResolveRoute.js
  src/app/ResolveRoute.test.js
  src/app/RootRoute.js
  src/app/components/modules/Header/index.jsx
  src/app/components/pages/CommunityRoles.jsx
  src/app/components/pages/PostsIndex.jsx
  src/app/redux/CommunityReducer.js
  src/app/redux/CommunitySaga.js
  src/app/redux/RootReducer.js
  src/app/redux/stateCleaner.js
  src/shared/RootSaga.js
Labels: WIP
